// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqnzswzkvmusbpgeydot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbnpzd3prdm11c2JwZ2V5ZG90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyOTU2NjksImV4cCI6MjA4ODg3MTY2OX0.m9XL5mWHEVDMjOb83fgDt2tv5_QTkmCeV60JRkgT9qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});